name: 🆘 General Support
description: Request general support or assistance
title: "[Team Name] <title-for-the-issue>"
labels: [General Support]
body:
- type: textarea
  attributes:
    label: Description of the issue
    description: A clear and concise description of the issue or problem you are facing.
  validations:
    required: true
- type: textarea
  attributes:
    label: Additional context
    description: |
      Links? References? Screenshots? Anything that will give us more context about the issue you are facing!
      
      Tip: You can attach images or files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
